FROM node:14-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
	&& apk add --no-cache --virtual .gyp \
        python3 \
        make \
        g++

# 安装 pnpm
RUN npm install -g pnpm --registry=https://registry.npmmirror.com